[tool.poetry]
name = "flask-job-scrapper"
version = "0.1.0"
description = ""
authors = ["DaehunGwak <rhkrgns56@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "2.31.0"
flask = "3.0.2"
beautifulsoup4 = "4.12.3"
selenium = "^4.23.1"
cachetools = "^5.5.0"
schedule = "^1.2.2"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
# https://beta.ruff.rs/docs/configuration/
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
